### ISSUE TITLE
Small problem

### ISSUE THREAD

**Issue by Fiocher** [itsschwer/pressure-drop#1]
I like this mod, but there are some problems in use:
"Unable to find command, try /help" is displayed after enter command, but item was successfully drop, and input box does not automatically close after complete input.
![Snipaste_2024-01-03_18-38-19](https://github.com/itsschwer/pressure-drop/assets/82749343/1d7cf41e-9ad8-4ffa-b2bd-487a10c30369)

**Comment by itsschwer** [comment]
This mod doesn't do anything with invalid commands and the release version does not have a `/help` command.

Do you have any other mods that implement chat commands or affect/use the in-game chat?

**Comment by Fiocher** [comment]
> This mod doesn't do anything with invalid commands and the release version does not have a `/help` command.
> 
> Do you have any other mods that implement chat commands or affect/use the in-game chat?

Thanks for your answer, I checked all mods and found that DropInMultiplayer was the problem.
https://thunderstore.io/package/niwith/DropinMultiplayer/

Paradoxically, this does not happen with Thrayonlosa's DropItem mod.
https://thunderstore.io/package/Thrayonlosa/DropItem/

**Comment by itsschwer** [comment]
Hey, just letting you know that I've pushed a new release (1.1.0) that reworks how chat commands are handled, and should hopefully improve compatibility with *DropInMultiplayer* — let me know if it worked!

**Comment by Fiocher** [comment]
> Hey, just letting you know that I've pushed a new release (1.1.0) that reworks how chat commands are handled, and should hopefully improve compatibility with _DropInMultiplayer_ — let me know if it worked!

It looks like it's all fixed, thank you!
